# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import informsistemo.main.utils.modelutils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_memberprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(editable=False, verbose_name='Created')),
                ('datetime_updated', models.DateTimeField(editable=False, verbose_name='Modified')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('image', models.ImageField(blank=True, null=True, upload_to=informsistemo.main.utils.modelutils.get_upload_path, verbose_name='Image')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Body')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug')),
                ('datetime_published', models.DateTimeField(verbose_name='Date Published')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is Published')),
                ('is_commentable', models.BooleanField(default=True, verbose_name='Is Commentable')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='users.MemberProfile', verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='DailyQuotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(editable=False, verbose_name='Created')),
                ('datetime_updated', models.DateTimeField(editable=False, verbose_name='Modified')),
                ('text', models.TextField(verbose_name='Text')),
                ('author', models.CharField(blank=True, max_length=30, null=True, verbose_name='Author')),
                ('pub_date', models.DateField(unique=True, verbose_name='For Date')),
            ],
            options={
                'verbose_name': 'Daily Quotation',
                'verbose_name_plural': 'Daily Quotations',
            },
        ),
        migrations.CreateModel(
            name='HomepageSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(editable=False, verbose_name='Created')),
                ('datetime_updated', models.DateTimeField(editable=False, verbose_name='Modified')),
                ('main_header_text', models.CharField(default='Solid Teamwork. Solid Results.', max_length=50, verbose_name='Header')),
                ('main_header_image', models.ImageField(blank=True, null=True, upload_to=informsistemo.main.utils.modelutils.get_upload_path, verbose_name='Image')),
                ('main_subtitle_text', models.TextField(blank=True, null=True, verbose_name='Short Description')),
                ('main_description_text', models.TextField(blank=True, null=True, verbose_name='Long Description')),
                ('events_header_text', models.CharField(default='Recent Events', max_length=50, verbose_name='Header')),
                ('events_subtitle_text', models.TextField(blank=True, null=True, verbose_name='Subtitle')),
                ('events_limit_items', models.PositiveIntegerField(default=3, verbose_name='Limit # of Items')),
                ('articles_header_text', models.CharField(default='Featured Articles', max_length=50, verbose_name='Header')),
                ('articles_subtitle_text', models.TextField(blank=True, null=True, verbose_name='Subtitle')),
                ('articles_subtitle_text2', models.TextField(blank=True, null=True, verbose_name='Subtitle 2')),
                ('articles_limit_items', models.PositiveIntegerField(default=3, verbose_name='Limit # of Items')),
                ('contact_header_text', models.CharField(default='Contact Us', max_length=50, verbose_name='Header')),
                ('contact_subtitle_text', models.TextField(blank=True, null=True, verbose_name='Subtitle')),
            ],
            options={
                'verbose_name': 'Homepage Setting',
                'verbose_name_plural': 'Homepage Settings',
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(editable=False, verbose_name='Created')),
                ('datetime_updated', models.DateTimeField(editable=False, verbose_name='Modified')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('icon', models.CharField(max_length=30, verbose_name='Font Awesome Icon')),
                ('url', models.URLField(max_length=255, verbose_name='URL')),
                ('order', models.IntegerField(default=1, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Social Account',
                'verbose_name_plural': 'Social Accounts',
            },
        ),
    ]
