# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesetting',
            name='main_header_text',
            field=models.CharField(default='Hello!', max_length=50, verbose_name='Header'),
        ),
    ]
