# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 02:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170114_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(editable=False, verbose_name='Created')),
                ('datetime_updated', models.DateTimeField(editable=False, verbose_name='Modified')),
                ('name_title', models.CharField(blank=True, max_length=30, verbose_name='Title')),
                ('last_name', models.CharField(max_length=35, verbose_name='Last Name')),
                ('first_name', models.CharField(max_length=35, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=35, verbose_name='Middle Name')),
                ('name_suffix', models.CharField(blank=True, max_length=30, verbose_name='Suffix')),
                ('nick_name', models.CharField(blank=True, max_length=30, verbose_name='Nickname')),
                ('birthdate', models.DateField(verbose_name='Birthdate')),
                ('birth_place', models.CharField(blank=True, max_length=255, null=True, verbose_name='Birth Place')),
                ('sex', models.PositiveIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True, verbose_name='Sex')),
                ('civil_status', models.PositiveIntegerField(blank=True, choices=[(1, 'Single'), (2, 'Married'), (3, 'Widowed'), (4, 'Separated/Divorced')], default=1, null=True, verbose_name='Civil Status')),
                ('nationality', models.CharField(blank=True, default='Filipino', max_length=30, null=True, verbose_name='Nationality')),
                ('occupation', models.CharField(blank=True, max_length=30, null=True, verbose_name='Occupation')),
                ('location', models.CharField(blank=True, max_length=30, null=True, verbose_name='Location')),
                ('personal_address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('personal_telephone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telephone #')),
                ('personal_mobile', models.CharField(blank=True, max_length=30, null=True, verbose_name='Mobile #')),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('business_address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('business_telephone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telephone #')),
                ('business_mobile', models.CharField(blank=True, max_length=30, null=True, verbose_name='Mobile #')),
                ('business_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Associate Profile',
                'verbose_name_plural': 'Associate Profiles',
            },
        ),
    ]
