# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_memberprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberprofile',
            options={'verbose_name': 'Member Profile', 'verbose_name_plural': 'Member Profiles'},
        ),
    ]
